### ISSUE TITLE
thanks brother

### ISSUE THREAD

**Issue by bettonna** [QuartzWarrior/Tip.cc-Autocollect#22]
thank you sir for your effort , I didn't test it yet but I wanted to ask that, my 1- question is this free version? and 2- question is there any bank risk with this app??  thank you again

**Comment by jamestaylor141** [comment]
Hey, this is the free version. And what do you mean by "bank risk"? You can't lose any money with this, if that's what you are asking. The worst that can happen is you getting banned on the account you are sniping drops from. So I'd suggest using alt accounts

**Comment by bettonna** [comment]
> Hey, this is the free version. And what do you mean by "bank risk"? You can't lose any money with this, if that's what you are asking. The worst that can happen is you getting banned on the account you are sniping drops from. So I'd suggest using alt accounts

thank you very much, example: I opened 3 accounts in discord, and they 3 acc' s are claiming the faucets , and later 3 acc's sending all earned moneys to another main account, I understood true, right? :/ sorry I don't know nothing about this , I'm learning  , and I hope the proxy option comes in other updates.

**Comment by jamestaylor141** [comment]
No worries! Yeah, that's true. There is an option to send all claimed money to the main account

**Comment by bettonna** [comment]
> No worries! Yeah, that's true. There is an option to send all claimed money to the main account

understand thank you brother, I'll try it later then :)

**Comment by QuartzWarrior** [comment]
@stefffkec thanks for handling this for me, I saw it but didn't understand a thing that was said, so didn't reply.

**Comment by bettonna** [comment]
> @stefffkec thanks for handling this for me, I saw it but didn't understand a thing that was said, so didn't reply.

sorry brother, my bad, I didn't see I wroten "bank" ,   I was mean "ban" , I wrote wrong sorry for that, 

also What should I do to avoid getting banned?

**Comment by bettonna** [comment]
I tried and it's giving this error,  
mtipcc_autocollect←[0m Whitelist enabled and drop not in whitelist, skipping drops-and-begging...   

 what should I do ? :/

**Comment by jamestaylor141** [comment]
Ohh you are also doing the tipcc server xD
You have 2 options (I suggest the second one):

1. Open config.json, find "CHANNEL_WHITELIST_ON": true, and change "true" to "false"
2. Find this:
    "CHANNEL_WHITELIST": [],
and change it to this:

    "CHANNEL_WHITELIST": [
        699702250531979325
    ],


And to avoid getting banned on tipcc, I suggest not claiming any redpackets, not claiming anything below 2s and not doing mathdrops (@QuartzWarrior I got banned cause the mathdrop claimer lagged (it just copy pasted the mathdrop question))

**Comment by jamestaylor141** [comment]
> @stefffkec thanks for handling this for me, I saw it but didn't understand a thing that was said, so didn't reply.

You are welcome! Also here if you need for the mathdrop. But no hurries, I anyways disabled it for now and it doesn't get much money xD
![image](https://github.com/user-attachments/assets/549a8182-39b3-4f3f-8e69-e0d2d6c16a74)

**Comment by bettonna** [comment]
> Ohh you are also doing the tipcc server xD You have 2 options (I suggest the second one):
> 
> 1. Open config.json, find "CHANNEL_WHITELIST_ON": true, and change "true" to "false"
> 2. Find this:
>    "CHANNEL_WHITELIST": [],
>    and change it to this:
>    "CHANNEL_WHITELIST": [
>    699702250531979325
>    ],
> 
> And to avoid getting banned on tipcc, I suggest not claiming any redpackets, not claiming anything below 2s and not doing mathdrops (@QuartzWarrior I got banned cause the mathdrop claimer lagged (it just copy pasted the mathdrop question))

aaa, okay my bad , thank you very much sir, ya I'm doing in tip.cc :)  , Also, is there any like tip.cc channel for claim airdrops? can I open 2 separate applications and use them on both the tip.cc site and the other site?  thanks again. 


also yes it's working now, joining drops but sometimes sending messages and sometimes not sending messages. I guess has bugs some. but it's working. but I was afraid of getting banned xd , I closed it for now but maybe I use later. thanks again :)

**Comment by QuartzWarrior** [comment]
> > @stefffkec thanks for handling this for me, I saw it but didn't understand a thing that was said, so didn't reply.
> 
> You are welcome! Also here if you need for the mathdrop. But no hurries, I anyways disabled it for now and it doesn't get much money xD ![image](https://private-user-images.githubusercontent.com/169636727/381192737-549a8182-39b3-4f3f-8e69-e0d2d6c16a74.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyMjAwNjQsIm5iZiI6MTczMDIxOTc2NCwicGF0aCI6Ii8xNjk2MzY3MjcvMzgxMTkyNzM3LTU0OWE4MTgyLTM5YjMtNGYzZi04ZTY5LWUwZDJkNmMxNmE3NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyOVQxNjM2MDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00YmYwYWMxMmRjMjkyYTVhMzc3ODU0Nzk5ZTJmNDBiYzYzNzk0YjkxMDg4Mzg3NzFlYTQ5NmE1ZDQzMGQxMGYwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.guMXhKUpt3hsqIzP99kLkIenNts5wwF9jruKiujKzCI)

that's odd... it should eval the equation and just just send it, ill look into it

**Comment by jamestaylor141** [comment]
> aaa, okay my bad , thank you very much sir, ya I'm doing in tip.cc :) , Also, is there any like tip.cc channel for claim airdrops? can I open 2 separate applications and use them on both the tip.cc site and the other site? thanks again.
> 
> also yes it's working now, joining drops but sometimes sending messages and sometimes not sending messages. I guess has bugs some. but it's working. but I was afraid of getting banned xd , I closed it for now but maybe I use later. thanks again :)

Yeah there is the drops-and-begging channel for tipcc server, also you can open 2 separate applications

**Comment by bettonna** [comment]
> > aaa, okay my bad , thank you very much sir, ya I'm doing in tip.cc :) , Also, is there any like tip.cc channel for claim airdrops? can I open 2 separate applications and use them on both the tip.cc site and the other site? thanks again.
> > also yes it's working now, joining drops but sometimes sending messages and sometimes not sending messages. I guess has bugs some. but it's working. but I was afraid of getting banned xd , I closed it for now but maybe I use later. thanks again :)
> 
> Yeah there is the drops-and-begging channel for tipcc server, also you can open 2 separate applications

hmm okay brother thank you, so is there any channel like tip.cc? do you know? or Are you using this app for any other channel?

**Comment by jamestaylor141** [comment]
I only do tipcc

**Comment by bettonna** [comment]
> I only do tipcc

okay thank you, I'm sorry I talked too much , I want to ask one last thing, Have you ever had the problem of sending messages bug sometimes?

**Comment by QuartzWarrior** [comment]
> > I only do tipcc
> 
> okay thank you, I'm sorry I talked too much , I want to ask one last thing, Have you ever had the problem of sending messages bug sometimes?

if they bug out, chances are you're under slowdown. Ill add better logging for that.

**Comment by bettonna** [comment]
> > > I only do tipcc
> > 
> > 
> > okay thank you, I'm sorry I talked too much , I want to ask one last thing, Have you ever had the problem of sending messages bug sometimes?
> 
> if they bug out, chances are you're under slowdown. Ill add better logging for that.


okay sir , thank you, I choosed default treshold:chance section like that 0.10:10 , is this normal? and I used app with default settings 200 and 310 etc. , so what should I do?  ,  maybe I did wrong thing I don't know

**Comment by QuartzWarrior** [comment]
> > I only do tipcc
> 
> okay thank you, I'm sorry I talked too much , I want to ask one last thing, Have you ever had the problem of sending messages bug sometimes?

can you provide me with the error you're getting when this happens? I'm working on a fix.



> > > > I only do tipcc
> > > 
> > > 
> > > okay thank you, I'm sorry I talked too much , I want to ask one last thing, Have you ever had the problem of sending messages bug sometimes?
> > 
> > 
> > if they bug out, chances are you're under slowdown. Ill add better logging for that.
> 
> okay sir , thank you, I choosed default treshold:chance section like that 0.10:10 , is this normal? and I used app with default settings 200 and 310 etc. , so what should I do? , maybe I did wrong thing I don't know

you can get rid of the threshold if you don't have a use for it, its for people who want better protection and know exactly what they want, so for more basic users, like you lets say, those other default settings look good tbh. The error for sending messages may be because of slow mode, but I'll add a fix if you can send me the error.




> Ohh you are also doing the tipcc server xD You have 2 options (I suggest the second one):
> 
> 1. Open config.json, find "CHANNEL_WHITELIST_ON": true, and change "true" to "false"
> 2. Find this:
>    "CHANNEL_WHITELIST": [],
>    and change it to this:
>    "CHANNEL_WHITELIST": [
>    699702250531979325
>    ],
> 
> And to avoid getting banned on tipcc, I suggest not claiming any redpackets, not claiming anything below 2s and not doing mathdrops (@QuartzWarrior I got banned cause the mathdrop claimer lagged (it just copy pasted the mathdrop question))

can you enable debug mode and send the printed stuff during a math drop? ( change line 85 where it says INFO to DEBUG ). I'll be able to fix it based off the info you provide me, as I haven't experienced this.

**Comment by bettonna** [comment]
> > > I only do tipcc
> > 
> > 
> > okay thank you, I'm sorry I talked too much , I want to ask one last thing, Have you ever had the problem of sending messages bug sometimes?
> 
> can you provide me with the error you're getting when this happens? I'm working on a fix.
> 
> > > > > I only do tipcc
> > > > 
> > > > 
> > > > okay thank you, I'm sorry I talked too much , I want to ask one last thing, Have you ever had the problem of sending messages bug sometimes?
> > > 
> > > 
> > > if they bug out, chances are you're under slowdown. Ill add better logging for that.
> > 
> > 
> > okay sir , thank you, I choosed default treshold:chance section like that 0.10:10 , is this normal? and I used app with default settings 200 and 310 etc. , so what should I do? , maybe I did wrong thing I don't know
> 
> you can get rid of the threshold if you don't have a use for it, its for people who want better protection and know exactly what they want, so for more basic users, like you lets say, those other default settings look good tbh. The error for sending messages may be because of slow mode, but I'll add a fix if you can send me the error.
> 
> > Ohh you are also doing the tipcc server xD You have 2 options (I suggest the second one):
> > 
> > 1. Open config.json, find "CHANNEL_WHITELIST_ON": true, and change "true" to "false"
> > 2. Find this:
> >    "CHANNEL_WHITELIST": [],
> >    and change it to this:
> >    "CHANNEL_WHITELIST": [
> >    699702250531979325
> >    ],
> > 
> > And to avoid getting banned on tipcc, I suggest not claiming any redpackets, not claiming anything below 2s and not doing mathdrops (@QuartzWarrior I got banned cause the mathdrop claimer lagged (it just copy pasted the mathdrop question))
> 
> can you enable debug mode and send the printed stuff during a math drop? ( change line 85 where it says INFO to DEBUG ). I'll be able to fix it based off the info you provide me, as I haven't experienced this.

okay sir thank you, when I try again later I'll send to you, thanks again

**Comment by jamestaylor141** [comment]
> can you enable debug mode and send the printed stuff during a math drop? ( change line 85 where it says INFO to DEBUG ). I'll be able to fix it based off the info you provide me, as I haven't experienced this.

Sorry, I tried recreating the bug but it didn't happen again

**Comment by QuartzWarrior** [comment]
> > can you enable debug mode and send the printed stuff during a math drop? ( change line 85 where it says INFO to DEBUG ). I'll be able to fix it based off the info you provide me, as I haven't experienced this.
> 
> Sorry, I tried recreating the bug but it didn't happen again

Alright, lmk if it does happen again, it shouldn't though

**Comment by bettonna** [comment]
hello sir how are you?, I tried the app today and I got some errors but it worked np, I saved errors and sharing with you,


this first error when connecting to discord showed;

←[34;1mINFO    ←[0m ←[35mdiscord.gateway←[0m Connected to Gateway (Session ID: *********). ←[30;1m(gateway.py:586)←[0m
Task exception was never retrieved
future: <Task finished name='Task-16' coro=<Client.change_presence() done, defined at C:\****\Python\Python312\Lib\site-packages\discord\client.py:1485> exception=TypeError("MessageToDict() got an unexpected keyword argument 'including_default_value_fields'")>
Traceback (most recent call last):
  File "C:\****\Python\Python312\Lib\site-packages\discord\client.py", line 1567, in change_presence
    await self.settings.edit(**payload)
  File "C:\****\Python\Python312\Lib\site-packages\discord\settings.py", line 1100, in edit
    existing = self.to_dict()
               ^^^^^^^^^^^^^^
  File "C:\******\Python\Python312\Lib\site-packages\discord\settings.py", line 146, in to_dict
    return MessageToDict(
           ^^^^^^^^^^^^^^
TypeError: MessageToDict() got an unexpected keyword argument 'including_default_value_fields'




2-  and later showed this error , I don't know why , 




←[31mERROR   ←[0m ←[35mtipcc_autocollect←[0m Timeout occurred while waiting for tip.cc message, skipping. ←[30;1m(tipcc_autocollect.py:680)←[0m
←[31mTraceback (most recent call last):
  File "C:*****\Python\Python312\Lib\asyncio\tasks.py", line 520, in wait_for
    return await fut
           ^^^^^^^^^
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:*****\Tip.cc-Autocollect-main\tipcc_autocollect.py", line 662, in on_message
    tip_cc_message = await client.wait_for(
                     ^^^^^^^^^^^^^^^^^^^^^^
  File "C:*****\Python\Python312\Lib\asyncio\tasks.py", line 519, in wait_for
    async with timeouts.timeout(timeout):
  File "C:*****\Python\Python312\Lib\asyncio\timeouts.py", line 115, in __aexit__
    raise TimeoutError from exc_val
TimeoutError←[0m




3- and this is joined airdrop but later didn't send message and gave this error,    





 ←[34;1mINFO    ←[0m ←[35mtipcc_autocollect←[0m Waited 6.25 seconds before proceeding. ←[30;1m(tipcc_autocollect.py:748)←[0m
←[30;1m02-Nov-2024 02:22:35 PM←[0m ←[31mERROR   ←[0m ←[35mdiscord.client←[0m Ignoring exception in on_message ←[30;1m(client.py:581)←[0m
←[31mTraceback (most recent call last):
  File "C:****\Python\Python312\Lib\asyncio\tasks.py", line 520, in wait_for
    return await fut
           ^^^^^^^^^
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:*****\Python\Python312\Lib\site-packages\discord\interactions.py", line 209, in _wrapped_interaction
    i = await state.client.wait_for(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:****\Python\Python312\Lib\asyncio\tasks.py", line 519, in wait_for
    async with timeouts.timeout(timeout):
  File "C:****\Python\Python312\Lib\asyncio\timeouts.py", line 115, in __aexit__
    raise TimeoutError from exc_val
TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:****\Python\Python312\Lib\site-packages\discord\client.py", line 507, in _run_event
    await coro(*args, **kwargs)
  File "C:****\Tip.cc-Autocollect-main\tipcc_autocollect.py", line 773, in on_message
    await button.click()
  File "C:*****\Python\Python312\Lib\site-packages\discord\components.py", line 227, in click
    return await _wrapped_interaction(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:*****\Python\Python312\Lib\site-packages\discord\interactions.py", line 215, in _wrapped_interaction
    raise InvalidData('Did not receive a response from Discord') from exc
discord.errors.InvalidData: Did not receive a response from Discord←[0m



I got these and shared with you sir, but app is working np, just giving some errors I don't know why,,  thanks again, I'll try again app later , later then if I got errors I'll share with you

**Comment by bettonna** [comment]
brother also if possible can you add proxy option please?? thanks again ,  

edited: I banned from channel, I don't know why, I disabled mathdrop and redpacket drops , and when it joined the airdrops sent messages not any problem but I banned in 2 days I don't know why :/   ,,,,,,,,,,,, I guess always need to be active in chat
